name: Deploy MPP Admin - NextJS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t watashiwazer0/mpp-admin  .
      - name: Publish Image to docker hub
        run: docker push watashiwazer0/mpp-admin:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull watashiwazer0/mpp-admin:latest
      - name: Delete old container
        run: docker rm -f mpp-admin-container
      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name mpp-admin-container watashiwazer0/mpp-admin
